// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjJ3Beym5aR7MkdkFRc1Ya5vnnmLqXYIQ',
    appId: '1:309143765216:web:298761d32feec9f6201085',
    messagingSenderId: '309143765216',
    projectId: 'crud-etudiant-firebase',
    authDomain: 'crud-etudiant-firebase.firebaseapp.com',
    storageBucket: 'crud-etudiant-firebase.appspot.com',
    measurementId: 'G-PF9E4TNGT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6XR85OTIx6uHyw2uC30vQpwJZ_2Pc-BA',
    appId: '1:309143765216:android:6930177169fef4fd201085',
    messagingSenderId: '309143765216',
    projectId: 'crud-etudiant-firebase',
    storageBucket: 'crud-etudiant-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0ZEY_wBcaLL02E_c7Sc06cFDOlbkZAeU',
    appId: '1:309143765216:ios:92c76846e68ad427201085',
    messagingSenderId: '309143765216',
    projectId: 'crud-etudiant-firebase',
    storageBucket: 'crud-etudiant-firebase.appspot.com',
    iosBundleId: 'sn.waref.waref',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0ZEY_wBcaLL02E_c7Sc06cFDOlbkZAeU',
    appId: '1:309143765216:ios:d448e572fdb7b29c201085',
    messagingSenderId: '309143765216',
    projectId: 'crud-etudiant-firebase',
    storageBucket: 'crud-etudiant-firebase.appspot.com',
    iosBundleId: 'sn.waref.waref.RunnerTests',
  );
}
